#pragma once

#define MAX_NUM_PROCESSES 1024
#define MAX_NUM_RESOURCES 1024
#define MAX_NUM_RESOURCES_PER_PROCESS 32
#define MAX_NUM_DESCRIPTORS_PER_PROCESS 32
#define MAX_NUM_MESSAGES_PER_QUEUE 128
#define MAX_NUM_STRINGS 32768
#define MAX_NUM_QUEUES 256 // MAX_NUM_STRINGS/MAX_NUM_MESSAGES_PER_QUEUE
#define MAX_MESSAGE_SIZE 128


#define STACK_SIZE        16384
// signals
#define MAX_SIGNALS 32
#define DSOS_SIGCHLD 0x1
#define DSOS_SIGHUP  0x2

// syscall errors
#define DSOS_ESYSCALL_ARGUMENT_OUT_OF_BOUNDS -1
#define DSOS_ESYSCALL_NOT_IMPLEMENTED -2
#define DSOS_ESYSCALL_OUT_OF_RANGE -3
#define DSOS_EFORK  -4
#define DSOS_EWAIT  -5
#define DSOS_ESPAWN  -6
#define DSOS_ESLEEP  -7
#define DSOS_ERESOURCECREATE -8
#define DSOS_ERESOURCEOPEN -9
#define DSOS_ERESOURCENOEXCL -10
#define DSOS_ERESOURCENOFD -11
#define DSOS_ERESOURCECLOSE -12
#define DSOS_ERESOURCEINUSE -13
#define DSOS_NO_MSG_RECEIVED -14
#define DSOS_NO_MSG_SENT -15
#define DSOS_EQUEUEOPEN -16
#define DSOS_SHUTDOWN_EXIT -17
#define DSOS_SHUTTING -18
// non-syscall errors
#define EAGAIN -101
#define INVALID_FD -102
#define INVALID_ATTRIBUTE -103
#define ATT_NOT_SET -104
#define BUFFER_TOO_SMALL -105
#define MSG_TOO_BIG -106
#define ACTION_NOT_ALLOWED -107
#define UNLINK_SCHEDULED -108
#define UNLINK_FAILED -109
#define INVALID_VALUE -110
#define UNEXP_NEGATIVE -111
#define OPERATION_NOT_AVAILABLE -112
#define INVALID_ID -113
#define LIST_INSERTION_ERROR -114

// syscall numbers
#define DSOS_MAX_SYSCALLS 32
#define DSOS_MAX_SYSCALLS_ARGS 8
#define DSOS_CALL_PREEMPT   1
#define DSOS_CALL_FORK      2
#define DSOS_CALL_WAIT      3
#define DSOS_CALL_EXIT      4
#define DSOS_CALL_SPAWN     5
#define DSOS_CALL_SLEEP     6
#define DSOS_CALL_OPEN_RESOURCE 7
#define DSOS_CALL_CLOSE_RESOURCE 8
#define DSOS_CALL_DESTROY_RESOURCE 9
#define DSOS_CALL_SHUTDOWN  10
#define DSOS_CALL_SEND_MSG  11
#define DSOS_CALL_RECV_MSG  12
#define DSOS_CALL_WAKEUP_QUEUE  13
#define DSOS_CALL_OPEN_QUEUE  14

//resources
#define DSOS_CREATE 0x1
#define DSOS_READ 0x2
#define DSOS_WRITE 0x3
#define DSOS_EXCL 0x4

// scheduling
#define ALPHA 0.5f
#define INTERVAL 100 // milliseconds for timer tick


// queues
#define DSOS_RDONLY     00000001
#define DSOS_WRONLY     00000002
#define DSOS_RDWR       00000003
#define DSOS_CREAT      00000010
#define DSOS_Q_EXCL     00000020
#define DSOS_NONBLOCK   00000040
// queue attributes constants
#define ATT_QUEUE_CURRENT_MESSAGES 0
#define ATT_QUEUE_MAX_MESSAGES 1
#define ATT_QUEUE_MESSAGE_SIZE 2
#define ATT_QUEUE_OPENINGS 3
#define ATT_QUEUE_UNLINK_REQUEST 4

// queue debug
#define PRINT_QUEUE_MESSAGES 0
#define PRINT_QUEUE_READERS 1
#define PRINT_QUEUE_WRITERS 1
#define PRINT_QUEUE_NONBLOCK 1
#define PRINT_QUEUE_ATTRIBUTES 1


